### ISSUE TITLE
Parameter 'DocumentObject' implicitly has an 'any' type

### ISSUE THREAD

**Issue by hanpama** [types/npm-jsonld#4]
Compilation trials throw an error message.

![foo](https://cloud.githubusercontent.com/assets/7418482/19257898/5a041cb4-8fae-11e6-95c4-55f8140dd48a.jpg)

```
typings/modules/jsonld/index.d.ts(104,47): error TS7006: Parameter 'DocumentObject' implicitly has an 'any' type.
```

``` typescript
export interface DocumentLoader {
  (url: string, callback: (err: Error | null, DocumentObject) => void): void;
}
```

https://github.com/types/npm-jsonld/blob/master/js/jsonld.d.ts#L21-L23

**Comment by blakeembrey** [comment]
Thanks for the catch. I previously relied on `ts-node` for these catches, but forgot that my compilation error optimisations means that any non-directly required TypeScript files don't error anymore.
